Adding support for aiida-atomistic
aiidateam/aiida-pseudo pull request #178
Opened 2024-11-22 20:32 UTC by mikibonacci

- in pseudo and cutoff we introduce the naming `LegacyStructureData` for th `orm.StructureData`.
- two additional tests, triggered only when we have atomistic installed (`HA` is `True`).

2024-11-27 09:17 UTC, sphuber requested changes
Thanks @mikibonacci requested some changes

2024-11-27 09:17 UTC, sphuber commented on tests/groups/family/test_pseudo.py
> +skip_atomistic = pytest.mark.skipif(not has_atomistic(), reason='Unable to import aiida-atomistic')
```suggestion
try:
    DataFactory('atomistic.structure')
except PluginError:
    has_atomistic = False
else:
    has_atomistic = True

skip_atomistic = pytest.mark.skipif(not has_atomistic, reason='Unable to import aiida-atomistic')
```

2024-11-29 11:12 UTC, mikibonacci commented
Hi @sphuber , thanks a lot for the very useful comments, I think I addressed all of them! Let me know if any other modification/fix is needed

2024-12-01 14:23 UTC, sphuber approved these changes

2024-12-01 14:24 UTC, merged