Docs: add troubleshooting section to the README.md
aiidateam/aiida-pseudo pull request #60
Opened 2021-04-01 08:14 UTC by sphuber

Fixes #59 and fixes #61 

Add first entry with suggestion on how to install a pseudo potential
family manually with the CLI if the automated commands fail, which is
often possible for unstable internet connections.

2021-04-08 16:29 UTC, mbercx requested changes
![image](https://user-images.githubusercontent.com/25607960/114062834-40876c80-9898-11eb-956a-5c36bdd1867e.png)

2021-04-08 16:29 UTC, mbercx commented on README.md
> +If you want to create a more specific family, for example an SSSP family, or a Pseudo-Dojo family, you should specify that with the `-T` option:
```suggestion
If you want to create a more specific family, for example an `SsspFamily`, or a `PseudoDojoFamily`, you can provide the corresponding entry point to the `--family-type/-T` option:
```

2021-04-08 16:29 UTC, mbercx commented on README.md
> +These failures are often due to unstable internet connections causing the download of the pseudo potential archive from the web to fail.
I apologise in advance for my OCD.

```suggestion
These failures are often due to unstable internet connections causing the download of the pseudopotential archive from the web to fail.
```

2021-04-08 16:29 UTC, mbercx commented on README.md
> +If you are experiencing problems with this automated install method, see the Troubleshooting section below for help.
```suggestion
If you are experiencing problems with this automated install method, see the [Troubleshooting section](#troubleshooting) below for help.
```

2021-04-08 16:29 UTC, mbercx commented on README.md
> +To install a pseudo potential family manually, run the following command:
```suggestion
To install a pseudopotential family manually, run the following command:
```

2021-04-08 16:29 UTC, mbercx commented on README.md
> +where `<ARCHIVE>` should be replaced with the pseudo potential archive and `<LABEL>` with the label to give to the family.
```suggestion
where `<ARCHIVE>` should be replaced with the pseudopotential archive and `<LABEL>` with the label to give to the family.
```

2021-04-08 16:29 UTC, mbercx commented on README.md
> +By default, the command will create a family of the base pseudo potential family type.
```suggestion
By default, the command will create a family of the base pseudopotential family type.
```

2021-04-08 16:29 UTC, mbercx commented on README.md
> +The available pseudo potential family classes can be listed with the command:
```suggestion
The available pseudopotential family classes can be listed with the command:
```

2021-04-08 16:29 UTC, mbercx commented on README.md
> +Any entry point that starts with `pseudo.family.` can potentially be used, depending on the type of pseudo potential archive.
```suggestion
Any entry point that starts with `pseudo.family.` can potentially be used, depending on the type of pseudopotential archive.
```

2021-04-09 07:26 UTC, sphuber commented
@mbercx thanks for the review. All nits have been picked clean. Also added an additional warning box about recommended cutoffs.

2021-04-09 07:51 UTC, mbercx approved these changes
Still found one of the buggers. Then my fur will be absolutely glowing. 👌

2021-04-09 07:51 UTC, mbercx commented on README.md
> +If this fails, you can specify the format manually with the `-F` option, for example, for a `.tar.gz` archice:
I found another one to pick! 🕷

```suggestion
If this fails, you can specify the format manually with the `--archive-format/-F` option, for example, for a `.tar.gz` archive:
```

2021-04-09 07:51 UTC, mbercx commented on README.md
> +| The functionality of some plugins, such as the workflow protocols of `aiida-quantumespresso`, may rely on recommended cutoffs to be defined for the pseudopotential family. Unlike the automated inst
Haha, I see you fixed the table before I could comment on it. ⚡

2021-04-09 10:40 UTC, mbercx approved these changes
My fur is itchy no more! 🐒

2021-04-09 10:45 UTC, merged